[package]
name = "reverie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = { version = "0.37.1", features = ['linked', 'debug'] }
winit = "0.27.5"
anyhow = "1.0.68"
ash-window = "0.11.0"
